In [21]:
%cd ../

e:\python\atomization-energy-regression


In [79]:
from src.dataset.molecule import get_molecule_name 
import scipy.io
import numpy as np
import matplotlib.pyplot as plt


In [80]:
data = scipy.io.loadmat('dataset\qm7.mat')

In [81]:
X = data['X'] # Coulomb matrices -> 7165 x 23 x 23
T = data['T'].T.squeeze() # atomization energies Y -> 7165 x 1
Z = data['Z'] # atomic charge -> 7165 x 23
R = data['R'] # cartesian coordinates -> 7165 x 23 x 3
data_train, data_test = {}, {}
molecule_name = get_molecule_name(data)


In [77]:
# print(molecule_name[3])
for i in range(20):
    print(Z[i], molecule_name[i])


[6. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] CH4X18
[6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2H6X15
[6. 6. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2H4X17
[6. 6. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2H2X19
[6. 6. 8. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2OH6X14
[6. 6. 8. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2OH4X16
[6. 8. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] COCH6X14
[6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C3H6X14
[6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C3H8X12
[6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C3H6X14
[6. 6. 6. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C3H4X16
[6. 6. 7. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] C2NH5X15
[6. 6. 7. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 

In [83]:
mols_infor = {}
for (idx, (atomic_charge, coor, mol_name, ener)) in enumerate(zip(Z, R, molecule_name, T)):
    if mol_name not in mols_infor:
        mols_infor[mol_name] = []
    else:
        mols_infor[mol_name].append(ener)
        # print(ener)
        # break
    # if mol_name == 'C3H6X14':
    #     # print(atomic_charge)
    #     # print(coor)
    #     print(ener)
    # break

    # if mol_name not in mols_infor:
    #     mols_infor[mol_name] = []
    # mols_infor[mol_name].append(ener)
    

C3H6X14
[6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C2OH4X16
[6. 6. 8. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 8. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C4H6X13
[6. 6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 6. 6. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C3NH9X10
[6. 6. 6. 7. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 6. 7. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C4H8X11
[6. 6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
NC3H7X12
[7. 6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7. 6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C4H8X11
[6. 6. 6. 6. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 6. 6. 6. 1. 1.

In [52]:
def mean_variance(array):
    mean = np.mean(array)
    var = np.sum((array - mean)**2) / (len(array))
    std = np.sqrt(var)
    return mean, var

In [ ]:
dis = []
label = []
for mol in mols_infor:
    if len(mols_infor[mol])< 3: continue
    mean, var = mean_variance(mols_infor[mol])
    std = np.sqrt(var)
    # if std < 40: continue
    dis.append(mean)
    label.append(mol)
    print(mol, mean, var, std, mols_infor[mol])

In [74]:
# plt.hist(dis, bins=2100)
# plt.legend()
# plt.show()

dis.sort()
diff = dis - np.roll(dis, 1)
diff

array([-1.22153687e+03,  1.28466064e+02,  4.44677734e+00,  1.65893555e+00,
        8.98437500e-02,  3.01269531e-01,  1.61401367e+00,  4.58422852e+00,
        5.68870850e+01,  4.81811523e-01,  2.69433594e+00,  7.25097656e-02,
        5.57653809e+00,  1.09375000e-01,  5.12421875e+01,  2.81982422e-01,
        1.51232910e+00,  4.21374512e+00,  1.44775391e+00,  5.89807129e+00,
        2.74340820e+00,  5.46386719e-01,  3.27026367e-01,  5.48217773e-01,
        3.52624512e+00,  2.85571289e+00,  1.30528564e+01,  2.68747559e+01,
        1.95935059e+00,  1.38061523e+00,  1.28991699e+00,  7.45239258e-01,
        2.09594727e-01,  3.72241211e+00,  4.29223633e+00,  2.96630859e-02,
        2.90148926e+00,  2.00659180e+00,  1.42626953e+00,  2.30590820e-01,
        8.00781250e-02,  7.19848633e-01,  7.03417969e+00,  4.44213867e+01,
        4.85839844e-01,  1.01953125e+00,  7.15820312e-01,  7.75146484e-02,
        4.91943359e-01,  3.24951172e-01,  2.43164062e+00,  8.39721680e-01,
        9.57031250e-02,  